<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Description>Riel Updater</Description>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyTitle>Riel Updater</AssemblyTitle>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <OutputPath>..\..\Program</OutputPath>
    <RootNamespace>Riel.Updater</RootNamespace>
    <ApplicationIcon>..\Riel.ico</ApplicationIcon>
    <Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GetText.NET" Version="11.0.10-preview.1" />
    <PackageReference Include="GetText.NET.WindowsForms" Version="11.0.10-preview.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Riel.Updater\Riel.Updater.csproj" />
  </ItemGroup>
</Project>