<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<Description>Riel Launcher</Description>
		<AssemblyTitle>Riel Launcher</AssemblyTitle>
		<OutputPath>..\..\Program</OutputPath>
		<RootNamespace>Riel.Launcher</RootNamespace>
		<AssemblyName>Riel</AssemblyName>
		<ApplicationIcon>..\Riel.ico</ApplicationIcon>
		<Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
	</PropertyGroup>
	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>
</Project>