<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Description>Riel Toolbox</Description>
    <AssemblyTitle>Riel Toolbox</AssemblyTitle>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputPath>..\..\Program</OutputPath>
    <ApplicationIcon>..\Riel.ico</ApplicationIcon>
    <RootNamespace>Riel.Toolbox</RootNamespace>
    <Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="5.0.0" />
    <PackageReference Include="Dirkster.AvalonDock.Serializer.Json" Version="5.0.0" />
    <PackageReference Include="GetText.NET" Version="11.0.10-preview.1" />
    <PackageReference Include="GetText.NET.Wpf" Version="11.0.10-preview.1" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Riel.Common\Riel.Common.csproj" />
    <ProjectReference Include="..\Riel.Models\Riel.Models.csproj" />
    <ProjectReference Include="..\Riel.Graphics\Riel.Graphics.csproj" />
  </ItemGroup>
</Project>