<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Description>Riel Simulation Library</Description>
		<AssemblyTitle>Riel Simulation Library</AssemblyTitle>
		<OutputPath>..\..\Program</OutputPath>
		<Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Common\**" />
		<EmbeddedResource Remove="Common\**" />
		<None Remove="Common\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5.1" />
		<PackageReference Include="MagicOnion.Client" Version="7.10.2" />
		<PackageReference Include="MagicOnion.Serialization.MemoryPack" Version="7.10.1-preview" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Riel.Models.Imported\Riel.Models.Imported.csproj" />
		<ProjectReference Include="..\Riel.Online\Riel.Online.csproj" />
		<ProjectReference Include="..\Riel.Runtime\Riel.Runtime.csproj" />
		<ProjectReference Include="..\Orts.Scripting.Api\Orts.Scripting.Api.csproj" />
		<PackageReference Include="GetText.NET" Version="11.0.10-preview.1" />
	</ItemGroup>
</Project>