<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Riel Proprietary Formats Library</Description>
    <AssemblyTitle>Riel Proprietary Formats Library</AssemblyTitle>
    <OutputPath>..\..\Program</OutputPath>
    <Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Riel.Common\Riel.Common.csproj" />
    <ProjectReference Include="..\Riel.Models\Riel.Models.csproj" />
  </ItemGroup>
</Project>