<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Riel.RuntimeSmoke</AssemblyName>
    <Description>Riel Runtime Smoke Test</Description>
    <OutputPath>../../../Program</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../ActivityRunner/ActivityRunner.csproj" />
  </ItemGroup>
</Project>
