<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <Description>Riel Menu</Description>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <AssemblyTitle>Riel Menu</AssemblyTitle>
    <OutputPath>..\..\Program</OutputPath>
    <ApplicationIcon>..\Riel.ico</ApplicationIcon>
    <RootNamespace>Riel.Menu</RootNamespace>
    <Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5.1" />
    <PackageReference Include="GetText.NET" Version="11.0.10-preview.1" />
    <PackageReference Include="GetText.NET.WindowsForms" Version="11.0.10-preview.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Riel.Models.Imported\Riel.Models.Imported.csproj" />
    <ProjectReference Include="..\Riel.Online\Riel.Online.csproj" />
    <ProjectReference Include="..\Riel.Updater\Riel.Updater.csproj" />
  </ItemGroup>
</Project>