<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Riel Updater Library</Description>
    <AssemblyTitle>Riel Updater Library</AssemblyTitle>
    <OutputPath>..\..\Program</OutputPath>
    <Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NuGet.Protocol" Version="7.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Riel.Common\Riel.Common.csproj" />
  </ItemGroup>
</Project>