<Project>
  <PropertyGroup>
    <RielPlatform Condition="'$(RielPlatform)' == '' AND $([MSBuild]::IsOSPlatform('Windows'))">windows</RielPlatform>
    <RielPlatform Condition="'$(RielPlatform)' == ''">linux</RielPlatform>
    <RielGraphicsBackend Condition="'$(RielGraphicsBackend)' == '' AND '$(RielPlatform)' == 'windows'">WindowsDX</RielGraphicsBackend>
    <RielGraphicsBackend Condition="'$(RielGraphicsBackend)' == ''">DesktopGL</RielGraphicsBackend>
    <MonoGameVersion>3.8.1.303</MonoGameVersion>
    <OutputPath>$(MSBuildThisFileDirectory)..\Program\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <RuntimeIdentifier Condition="'$(RielPlatform)' == 'windows'">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(RielPlatform)' != 'windows'">linux-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
